export const API_STATUS = {
    OK: "OK",
    NOT_FOUND: "NOT_FOUND",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    DB_ERROR: "DB_ERROR",
    INVALID_INPUT: "INVALID_INPUT",
    EXISTED: "EXISTED",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    PERMISSION_DENIED: "PERMISSION_DENIED",
    SEND_EMAIL_ERROR: "SEND_EMAIL_ERROR",
    RECEIVE_EMAIL_ERROR: "RECEIVE_EMAIL_ERROR",
};

export const HTTP_METHOD = {
    GET: "GET",
    PUT: "PUT",
    DELETE: "DELETE",
    POST: "POST",
};